---
- hosts: web
  become: true
  tasks:
    - name: Update the apt-get
      apt:
        update_cache: yes

    - name: Install apache2
      apt:
        name: "apache2"
        state: present

    - name: Create a directory if it does not exist
      file:
        path: "{{ website_path }}"
        state: directory

    - name: Copy new temple file index.html.j2 file
      template:
        src: "index.html.j2"
        dest: "{{ website_path }}/index.html"

    - name: Copy configuration file for apache
      copy:
        src: "pascal.conf"
        dest: "/etc/apache2/sites-available/pascal.conf"

    - name: Enable site for pascal.conf
      command:
        a2ensite pascal.conf

    - name: Disable site for default.conf
      command:
        a2dissite 000-default.conf

    - name: Restart apache2 server
      service:
        name: apache2
        state: restarted